### DISCUSSION TITLE
Run only after code changes

### DISCUSSION THREAD

**Discussion by jerone** [FantasticFiasco/action-update-license-year#276] [Ideas]
I wanted to run this Github Action **only after code changes** in the new year. I didn't see that [scenario](https://github.com/FantasticFiasco/action-update-license-year#scenarios) in the readme. After some trial and error I was able to include it in my CI script, which runs on every PR and after every merge to master-branch:

```yaml
name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint: ...

  test: ...

  copyright:
    # This line will prevent running this step in a PR.
    # Change `master` to `main` or any other name for your main branch.
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Replace '--merge' with '--rebase' to rebase the commits onto the base
        # branch, or with '--squash' to squash the commits into one commit and merge
        # it into the base branch.
        # For more information regarding the merge command, please see
        # https://cli.github.com/manual/gh_pr_merge.
        gh pr merge --merge --delete-branch
```

Might be useful for others.

**Comment by FantasticFiasco** [comment]
Hi @jerone!

Let me see if I understand the workflow. It's triggered either by pull requests or commits on master, and the `if` statement on the `copyright` job makes sure that the job only executes on master. Then we do the ordinary steps, we checkout, we run this action, and possibly there are files to update and possibly there aren't. Are we considering both situations in the final `Merge PR` step? I.e.:

1. How will the merge command behave in the situation where nothing has changed.
2. How will the merge command behave in the situation where files have been updated. Is it because this action creates a branch and opens a PR that this command works without having to specify the specific PR to merge?

**Reply by jerone** [reply]
> 1.How will the merge command behave in the situation where nothing has changed.

The CI action is linked to the `master` branch, which is **only** triggered when something changes to that branch (via commit to the `master` branch, or via PR (which is excluded)). There is no cron schedule.

> 2.How will the merge command behave in the situation where files have been updated. Is it because this action creates a branch and opens a PR that this command works without having to specify the specific PR to merge?

When something did change to the `master` branch, we want the copyright action to trigger, create branch and merge it.

**Reply by FantasticFiasco** [reply]
Sorry, but what I meant with 1 was that even though I understand that code changed, it doesn't mean that copyright years needed changing, thus it's not always the case that a new branch was created and a new PR opened for the final step to merge.

Do you have any link to a GitHub Actions workflow where this is running?

**Reply by jerone** [reply]
What I needed was a copyright year update only after a code (or anything) changes in the repository in the new year. An cronjob schedule would just create a PR (even though no code change happened in the new year (yet)).

My example runs the `copyright` job every time a change happens to the `master` branch, which guaranties an code change was made.
And only the first time, the copyright is updated and a branch is created to be (auto-)merged. Every sequential runs, nothing happens.

Usually your CI jobs run on PR too, that's why I excluded that route in the CI script. Otherwise it would create an infinity loop for every new change of that year (which almost happened when I introduced this job step :P)

Example: https://github.com/jerone/eslint-formatter-checklist/actions

**Reply by FantasticFiasco** [reply]
I see, nice! Yes this would probably be beneficial for other developers as well! If you are up for it and have the bandwidth to create the PR I wouldn't want to be in the way, but if you don't I would be happy to update the documentation myself.

**Reply by jerone** [reply]
Go ahead! My description above needed apparently more context to explain what I thought was useful. I'm sure you can reword it much better.

**Reply by FantasticFiasco** [reply]
The documentation has now been updated, and you have been rightfully attributed in the final chapter of the README. Thanks for telling me about the scenario!

**Reply by jerone** [reply]
Awesome. So much better explained! 👍

**Comment by jerone** [comment]
Hi @FantasticFiasco. I just found two (small) issues with the [current implementation of this template](https://github.com/FantasticFiasco/action-update-license-year#i-want-to-update-my-license-on-first-commit-each-year-and-i-want-it-merged):

First, the trailing dot `.` behind the url, is appended to the url by GitHub, creating an invalid link: [https://cli.github.com/manual/gh_pr_merge.](https://cli.github.com/manual/gh_pr_merge.)

Second, when there is no change, the merge code is still triggered, trying to merge the PR that is linked to the current branch. 
As the PR is already merged, `gh` stops with the message [`! Pull request #2 was already merged`](https://github.com/jerone/eslint-formatter-checklist/actions/runs/2955988325/jobs/4726517685#step:4:8). This is not bad, but also not expected.
The real problem is actually, when you just created a new repository, your copyright year is up-to-date, and the merge code is trying to merge the branch that has no PR linked to it. This creates an error [`no pull requests found for branch "license/copyright-to-2022"`](https://github.com/jerone/assert-includes/actions/runs/3339246897/jobs/5527953601#step:4:8).

I don't know (yet) how to resolve this issue. It's not great to have this CI action failing on every push.

Is there an output variable available to use in an `if`-statement, like an status or PR id or branch name?

**Comment by FantasticFiasco** [comment]
> First, the trailing dot . behind the url, is appended to the url by GitHub, creating an invalid link: https://cli.github.com/manual/gh_pr_merge.

This is not on the rendered page on GitHub right, this is in your editor? What editor are you using?

> I don't know (yet) how to resolve this issue. It's not great to have this CI action failing on every push.

Not great at all 🤣  I'll look into it, but don't currently have the bandwidth. Possibly the action should return a result, as you've suggested, that can control the flow of the action.

**Reply by jerone** [reply]
> > First, the trailing dot . behind the url, is appended to the url by GitHub, creating an invalid link: https://cli.github.com/manual/gh_pr_merge.
> 
> This is not on the rendered page on GitHub right, this is in your editor? What editor are you using?

Just in the browser (Firefox):
![image](https://user-images.githubusercontent.com/55841/198539973-acac2113-e619-4dba-85d7-ac5a52cf8b19.png)



> > I don't know (yet) how to resolve this issue. It's not great to have this CI action failing on every push.
> 
> Not great at all 🤣 I'll look into it, but don't currently have the bandwidth. Possibly the action should return a result, as you've suggested, that can control the flow of the action.

I'm looking into using `gh` to detect if there is an PR available on that branch and putting an `if`-statement before the merge. But I haven't got it working yet. Will keep you updated.

**Reply by jerone** [reply]
So, it looks like I incorrectly thought that I would be able to get the corresponding PR from the branch created by this Action. But the branch is created via API.

I then hoped to get the corresponding PR based on the branch *name* created by this Action, but there appears to be **no** [outputs](https://github.com/FantasticFiasco/action-update-license-year/blob/master/action.yml). Correct?

So, without any outputs, it's impossible to know which branch is created (name is variable every year), and which corresponding PR belongs to that.
Would it be easy to include output variables for?:
* year - number
* branch name - string
* has PR - boolean
* PR id - number

**Reply by jerone** [reply]
Current not-working test code:
```yml
      - uses: FantasticFiasco/action-update-license-year@v2
        id: LICENSEYEAR
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: current-pr
        with:
          filterOutClosed: true # Only return if PR is still open.
      - env:
          TEST: ${{ toJson(steps) }}
        run: echo "$TEST"
      - name: Merge PR
        if: success() && steps.current-pr.outputs.number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --rebase --delete-branch
```

Interesting: https://localheinz.com/blog/2020/06/15/merging-pull-requests-with-github-actions/
