### ISSUE TITLE
Modifying Commit Author

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [FantasticFiasco/action-update-license-year#119]
I think this action is really useful 🙌  And you certainly saved the time of many others as well :)

## Description

It would be great if one could specify the commit author configuration for the PR.

## Existing example

The "Deploy to GitHub Pages" action allows you to do that for example: https://github.com/marketplace/actions/deploy-to-github-pages

See https://github.com/marketplace/actions/deploy-to-github-pages#optional-choices.

**Comment by FantasticFiasco** [comment]
Hi @creativecreatorormaybenot!

Glad you think you saved some time using this action 😄 

It is the parameters `GIT_CONFIG_NAME` and `GIT_CONFIG_EMAIL` you are thinking of, which currently in this action is hardcoded to `github-actions` and `github-actions@github.com`?

**Comment by creativecreatorormaybenot** [comment]
@FantasticFiasco Yes, exactly. It would be amazing to sign the commits of course, however, I assume that this would be too complicated.

If you look at the commit in my repo (https://github.com/creativecreatorormaybenot/funvas/commit/039e652835701f85b28a65829adb117b769280ab), it looks pretty ugly because of two things: 1. it has @github-actions as the PR author (which is okay), however, it has a user without an icon as the commit author. That should likely have my config instead (i.e. my name and email) 👍

**Comment by FantasticFiasco** [comment]
I think we can support git name and e-mail without any breaking changes, and I don't foresee any problems with the implementation either.

Regarding GPG signing, please open a new issue regarding that and we'll see what we can do about it. I think I need your input there, because it would most probably require you to save your private key in GitHub, and I would argue that not everybody would be comfortable doing so.

**Comment by creativecreatorormaybenot** [comment]
@FantasticFiasco I agree - I probably do not even want to open an issue because of that.

**Comment by FantasticFiasco** [comment]
@creativecreatorormaybenot, would you be able to update your configuration, and replace `<your name>` and `<your e-mail>` with relevant values.

```yaml
- uses: FantasticFiasco/action-update-license-year@66564cc720675678f03c008d254ebbf5f22609ac
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: '**/LICENSE'
        commitTitle: Update copyright year in LICENSE file(s)
        prTitle: Update copyright year in LICENSE file(s)
        prBody: New Year is here and we want to keep up with time :)
        assignees: creativecreatorormaybenot
        commitAuthorName: <your name>
        commitAuthorEmail: <your e-mail>
```

If you find that the behavior meets your expectations, I'll continue with releasing this officially.
