### ISSUE TITLE
Document how to update custom file through RegExp and LICENSE file in one PR

### ISSUE THREAD

**Issue by mondeja** [FantasticFiasco/action-update-license-year#138]
**Is your feature request related to a problem? Please describe.**
I want to update my LICENSE file along with other file in my project, using for this other file a regular expression transform. 

**Describe the solution you'd like**
I would like to update the two files in one pull request.

**Describe alternatives you've considered**
Make two updates in different pull requests. I think that the current implementation forces to use this solution. Please, correct me if I'm wrong.

**Additional context**
Maybe a parameter that could skip the pull request creation would be the more flexible solution. It would allow me to create my own complete year-updating logic using action-update-license-year along with another action like https://github.com/peter-evans/create-pull-request

**Comment by FantasticFiasco** [comment]
Hi!

Wouldn't this be possible using two different jobs in the same GitHub Actions workflow? One job would update the license, and the other job would update the additional files with a transform. Given the jobs act on the same branch, their changes would be a part of the same pull request.

**Comment by FantasticFiasco** [comment]
I did a test in the [following repo](https://github.com/FantasticFiasco/license-test/pulls). It works like a charm, but one gotcha was that you have to chain the jobs using `needs`. Otherwise we end up with a race condition where each job wishes to create the branch and the PR.

The full configuration looks like this.

```yaml
name: Update copyright year(s) in license file

on: workflow_dispatch

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: FantasticFiasco/action-update-license-year@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  
  source:
    needs: [license]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: FantasticFiasco/action-update-license-year@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: "*.js"
        transform: (?<=Some license )(?<from>\d{4})-\d{4}
```
