### ISSUE TITLE
"Update license copyright year" action does not seem to work

### ISSUE THREAD

**Issue by alex4200** [FantasticFiasco/action-update-license-year#160]
**Describe the bug**

I tried to follow the description [HERE](https://github.com/marketplace/actions/update-license-copyright-year-s) to implement an action that updates the copyright year in the `LICENSE`, but it did nothing. It did not change the `LICENSE` file. 

**To Reproduce**

I created the following file `github_actions_demo.yml` in the folder `.github/workflow`:

```
name: GitHub Actions Demo
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
```

**Expected behavior**

I was expecting that the copyright in my LICENSE file (in a private test repo) has been updated from the text

`Copyright (c) 2020, alex4200
`

to the text

`Copyright (c) 2020, 2021, alex4200
`

or 

`Copyright (c) 2020-2021, alex4200
`

**Comment by FantasticFiasco** [comment]
Which license are you using?

**Comment by alex4200** [comment]
`BSD 3-Clause "New" or "Revised" License`

**Comment by FantasticFiasco** [comment]
Just making sure you named the directory "workflows", can you verify that?

Did the workflow run? Did any of the steps fail? If yes, is there an error message?

**Comment by alex4200** [comment]
I just tried again with the following yaml file for the action:

```
name: GitHub Actions Demo
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          path: |
            README.md
```

and here I got an error 

`Error: Default transform is not valid on "./README.md"`

In the end I need to update the copyright also in a file named `README.md`. Do I misunderstand your examples?
