### ISSUE TITLE
Is there a specific reason to leave out merging of the branch?

### ISSUE THREAD

**Issue by utkarshsethi** [FantasticFiasco/action-update-license-year#213]
**Is your feature request related to a problem? Please describe.**
Having to manually merge branch after license update.

**Describe the solution you'd like**
Auto merge and deletion of the branch

**Describe alternatives you've considered**
I've written additional job to merge and delete the branch

Can submit a pr to include in this. or if it's left out a reason, a documentation entry to guide others looking for this.

**Comment by FantasticFiasco** [comment]
Hi @utkarshsethi!

The reasoning for excluding the proposed feature was because I didn't think anyone trusted the codebase to automatically merge the created PR. But here you are 😄 

How did you solve it? Does it require changes to the codebase or did you chained additional steps in the workflow to merge the PR and then delete the branch?

**Comment by utkarshsethi** [comment]
> Hi @utkarshsethi!
> 
> The reasoning for excluding the proposed feature was because I didn't think anyone trusted the codebase to automatically merge the created PR. But here you are 😄

So you can maybe just give it as a suggestion in the README. Which will offer the users the option to choose.

> How did you solve it? Does it require changes to the codebase or did you chained additional steps in the workflow to merge the PR and then delete the branch?

I just chained gh cli steps

```
        # Auto Merge license -> master
      - uses: actions/checkout@master

        #merge and delete
      - name: Auto Merge license -> master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh pr checkout license
          gh pr merge -d -m
```
