### ISSUE TITLE
Glob for candidates

### ISSUE THREAD

**Issue by windymelt** [FantasticFiasco/action-update-license-year#312]
**Is your feature request related to a problem? Please describe.**

I'm going to use this action to update copyright information in template file (for XSlate template engine) using custom transform feature.

Of course, not all of template contains copyright year information. Currently I have to specify accurate file path that contains copyright year manually.

**Describe the solution you'd like**

If this action provides option that ignores regex mismatch, I will be able to use glob to specify target candidates.

**Describe alternatives you've considered**

**Additional context**

my transform is like this:

```yaml
jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: templates/**/*.html
          transform: '(?<=<div class="copyright">Copyright &copy; )(?<from>\d{4})?(&ndash;)?(\d{4})?'
```

some of template contains following line:

```html
<div class="copyright">Copyright &copy; 2005&ndash;2022 <a href="https://example.com/">Foobar Inc</a>. All Rights Reserved.</div>
```
