### ISSUE TITLE
Explain how to test it on my repository

### ISSUE THREAD

**Issue by spl** [FantasticFiasco/action-update-license-year#39]
**Is your feature request related to a problem? Please describe.**

This project is a great idea! I'm hoping it will save me (and others) time/worry. But first, I'd like to test it out by triggering it on my repository.

**Describe the solution you'd like**

Can you explain how to, say, trigger `action-update-license-year` to determine if it worked correctly? If I want to use it, I'd like to know that it worked before January of next year.

Here's the kind of scenario I'm thinking about:

1. I create a PR to my repo with an action that, when run immediately, will create a PR to update the copyright.
2. Then, depending on whether `action-update-license-year` worked, I'm faced with a decision:
   * Satisfied, I go to 3.
   * Dissatisfied, I file a bug report with you and point you to my failed PR. Hopefully, the error is enough to help you fix any problem. Once fixed, I re-run `action-update-license-year` and return to 2.
3. I change the action in my PR to schedule it as you've shown in your README.

Ideally, you could update your README with how to work through a scenario such as the above. This would help potential users other than myself. Thanks!

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by FantasticFiasco** [comment]
I’ll see if I cannot create a repository for you, and I’ll see what I can do about the lacking documentation. I’ll get back to you when I get home from work.

**Comment by FantasticFiasco** [comment]
Clearly there's not enough information in `README.md`, and I'll have to do a better job there, but until then this is what you can do to test the action.

Start with making sure that your current licence file is inaccurate, i.e. isn't specifying 2020. Then create a new workflow in your repository. The name of the YAML file is unimportant but you have to place it in the directory `.github/workflows/`. Add the following content to the file.

```yml
name: Update copyright year(s) in license file

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Update license copyright year(s)
        uses: FantasticFiasco/action-update-license-year@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

A commit to your repository will trigger the action, and about a half of a minute after you pushed your code there should be a PR waiting for you. I just tested this in a new clean repo, you can find it [here](https://github.com/FantasticFiasco/action-update-license-year-push-trigger).
