### ISSUE TITLE
Update one or more arbitrary files with copyright years

### ISSUE THREAD

**Issue by spl** [FantasticFiasco/action-update-license-year#43]
**Is your feature request related to a problem? Please describe.**

A repository might have a `LICENSE` or a `license.md`. It might have both a `LICENSE-APACHE` and a `LICENSE-MIT`. The README might mention the copyright. Also, code headers often have copyright years in them. How can I update all of them?

**Describe the solution you'd like**

It would be useful to have the action update the copyright year in a number of different files, as mentioned above.

**Describe alternatives you've considered**

I suppose there are a number of possible solutions for determining which files to update:

* Search for something like “copyright” (case-insensitive) in all files
* Support explicit file listing when configuring the action
* Support file globs for choosing multiple files (e.g. all the JavaScript files such as `src/**/*.js`)

And there are multiple possibilities for determining the text to change:

* ”Copyright” followed by something
* A user-configured text pattern to match

I haven't given any thought to what the best solution is.

**Additional context**

N/A

**Comment by FantasticFiasco** [comment]
I'll fix the obvious bugs before starting on this one.

**Comment by FantasticFiasco** [comment]
Aiming at some use-cases would lead us to the necessary configuration. I'll start with defining the ones I can come up with, and if you envision any other please feel free to add them.

Specify configuration for the following use-cases:

- [ ] License file is not called `LICENSE`, but `LICENSE.md`, `license.md` or something else
- [ ] License is not among the supported, let the user define their own transform
- [ ] A mono-repo contains multiple projects, all with their own license. How do we upgrade them all, or upgrade them individually?
- [ ] Copyright is defined in source files, how do we update those?

**Comment by tenshiAMD** [comment]
@FantasticFiasco let me give you my idea and suggestions regarding this matter. 

I think it will be great if we can add repo paths for the LICENSE files in the configuration and those paths will be scanned by your action workflow.

**Comment by FantasticFiasco** [comment]
@tenshiAMD Would your suggestion match *"A mono-repo contains multiple projects, all with their own license. How do we update them all, or update them individually?"* above, or is your suggestion something else?

**Comment by tenshiAMD** [comment]
@FantasticFiasco I think my suggestion is different and is more like for single repository configuration like I've mentioned in issue https://github.com/FantasticFiasco/action-update-license-year/issues/57. Your idea is more like an organization-wide or global configuration sort of.

**Comment by FantasticFiasco** [comment]
@spl and @tenshiAMD, can you take a look at the following configuration proposals for the different use-cases and tell me what you think. I haven't started to look at any implementation yet, the proposal might change slightly during that phase.

- [ ] A repository contains a license file that isn't called LICENSE, but `LICENSE.md`, `license.md` or something else

```yaml
- uses: FantasticFiasco/action-update-license-year@v1
  with:
    - path: LICENSE.md
```

- [ ] A repository contains multiple license files

```yaml
- uses: FantasticFiasco/action-update-license-year@v1
  with:
    - path: |
        LICENSE-APACHE
        LICENSE-MIT
```

- [ ] A repository contains a license that isn't among the officially supported, let the user define their own transform

TODO

- [ ] A mono-repository contains multiple projects, all with their own license

```yaml
- uses: FantasticFiasco/action-update-license-year@v1
  with:
    - path: packages/*/LICENSE
```

- [ ] Copyright is defined in source files

```yaml
- uses: FantasticFiasco/action-update-license-year@v1
  with:
    - path: src/**/*.js
```
