### ISSUE TITLE
Failing to push to branch when using a GitHub app token

### ISSUE THREAD

**Issue by zeshuaro** [FantasticFiasco/action-update-license-year#612]
**Describe the bug**

When using the token generated by [actions/create-github-app-token](https://github.com/actions/create-github-app-token) and provided as the `token` parameter, the action fails with the following error:

```
Run FantasticFiasco/action-update-license-year@v3.0.2
  with:
    token: ***
    commitTitle: docs(license): update copyright year to {{ currentYear }}
    prTitle: docs(license): update copyright year to {{ currentYear }}
    labels: documentation
    path: LICENSE
    branchName: license/copyright-to-{{currentYear}}
    commitAuthorName: github-actions
    commitAuthorEmail: github-actions@github.com
Working directory: /home/runner/work/firestore_cache/firestore_cache
Current year is "[2](https://github.com/zeshuaro/firestore_cache/actions/runs/12608914191/job/35141891620#step:4:2)025"
Checkout new branch named "license/copyright-to-2025"
Found 1 file(s) matching the path "LICENSE"
Update license in "./LICENSE"
Error: Error pushing changes to new branch: Command failed: git push --set-upstream origin license/copyright-to-202[5](https://github.com/zeshuaro/firestore_cache/actions/runs/12608914191/job/35141891620#step:4:5)
fatal: could not read Username for 'https://github.com': No such device or address
```

**To Reproduce**

Use the following workflow with a GitHub app details:

```
jobs:
  update-license:
    name: Update license year
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App token 🔑
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Update license year 🪪
        uses: FantasticFiasco/action-update-license-year@v3.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          commitTitle: "docs(license): update copyright year to {{ currentYear }}"
          prTitle: "docs(license): update copyright year to {{ currentYear }}"
          labels: documentation
```

**Expected behavior**

The workflow should work with a GitHub app token

**Screenshots**

See this example workflow: https://github.com/zeshuaro/firestore_cache/actions/runs/12608914191/job/35141891620

**Desktop (please complete the following information):**

- OS: ubuntu
- Version 3.0.2

**Additional context**

N/A
